#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $KC_DB_USERNAME WITH PASSWORD '$KC_DB_PASSWORD';
	CREATE DATABASE $KC_DB_URL_DATABASE;
	GRANT ALL PRIVILEGES ON DATABASE $KC_DB_URL_DATABASE TO $KC_DB_USERNAME;
    \connect $KC_DB_URL_DATABASE $POSTGRES_USER
    GRANT ALL ON SCHEMA public TO $KC_DB_USERNAME;
EOSQL
