#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER '$KEYCLOAK_USER';
     WITH PASSWORD '$KEYCLOAK_PASSWORD';
	CREATE DATABASE '$KEYCLOAK_DB_NAME';
	GRANT ALL PRIVILEGES ON DATABASE '$KEYCLOAK_DB_NAME' TO '$KEYCLOAK_USER';
    \connect $KEYCLOAK_DB_NAME $POSTGRES_USER
    GRANT ALL ON SCHEMA public TO $KEYCLOAK_USER;

EOSQL