apiVersion: v1
data:
  init.sh: "#!/bin/bash\r\nset -e\r\n\r\npsql -v ON_ERROR_STOP=1 --username \"$POSTGRES_USER\"
    --dbname \"$POSTGRES_DB\" <<-EOSQL\r\n\tCREATE USER '$KEYCLOAK_USER';\r\n     WITH
    PASSWORD '$KEYCLOAK_PASSWORD';\r\n\tCREATE DATABASE '$KEYCLOAK_DB_NAME';\r\n\tGRANT
    ALL PRIVILEGES ON DATABASE '$KEYCLOAK_DB_NAME' TO '$KEYCLOAK_USER';\r\n    \\connect
    $KEYCLOAK_DB_NAME $POSTGRES_USER\r\n    GRANT ALL ON SCHEMA public TO $KEYCLOAK_USER;\r\n\r\nEOSQL"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-11T16:05:27Z"
  name: keycloak-database
  namespace: default
  resourceVersion: "22317"
  uid: 9990d392-e2f0-4639-80d9-e8ee6a11bcfe