apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
  namespace: default
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "8282"
      port: 8282
      targetPort: 8282
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
